feat: backlog/choose-render-or-pickup-mode-in-collector
ftrackhq/ftrack-connect-pipeline-nuke pull request #10
Opened 2023-03-13 16:39 UTC by henriknorin-ftrack

Resolves 

- [ ] I have added automatic tests where applicable.
- [ ] The PR contains a description of what has been changed.
- [ ] The description contains manual test instructions.
- [X] The PR contains updates to the release notes.
- [ ] I have verified that the documentation is still up to date.

## Changes

* Enhanced image sequence and movie publisher UI - migrated options from exporter to collector
* Added movie component to image sequence publisher, but optional and disabled by default, in case both image sequence and movie is required to be published at the same version.
* Reviewable component is now optional.
* Reviewable component now reuses the movie exporter plugin to minimise duplicate code.

## Test

Test all linear combinations of publish with image sequence and movie, trying all collect modes and with reviewable.

2023-03-14 10:24 UTC, lluisCM requested changes
Please align to unreal. Separate movie collectors from image sequence collector, etc...

2023-03-14 10:24 UTC, lluisCM commented on resource/definitions/publisher/image-sequence-nuke-publish.json
> +      "name": "movie",
Why are we publishing a movie component in the image_sequence publisher?
Movie should be published with the movie publisher.

2023-03-14 10:24 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
> +        '''Fetch all selected nodes in nuke, match against class name if supplied in *options*'''
Keep the line of docstrings comments to 79 char max

2023-03-14 10:24 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
> +            ):
Why doing this? classname is not in the definitions options neither in the widget...

2023-03-14 10:24 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
I think we should have a collector for image sequence and a different collector for a movie. So it's easier to maintain and the code is cleaner. (Look at unreal, it has the reviewable collector that collects movies and the image sequence collector that only collects image sequences)

2023-03-14 10:24 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
> +        else:
Better to specify elif mode == pickup

2023-03-14 10:24 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
> +            result = {'image_sequence_path': image_sequence_path}
This is only for the reviewable right? please don't mix it up, put it in a separated collector.

2023-03-14 10:24 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
Please separate in different files. Check unreal.

2023-03-14 11:30 UTC, henriknorin-ftrack reviewed
Pushed a new commit attending the changes

2023-03-14 11:30 UTC, henriknorin-ftrack commented on resource/definitions/publisher/image-sequence-nuke-publish.json
> +      "name": "movie",
In VFX/post, you almost always want to publish both the high res image sequence and a proxy (movie) for editorial purposes. Forcing the artist to publish a second version makes review and project management difficult as they would need to track two versions in ftrack (that might differ in version # etc etc)

2023-03-14 11:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
Agree to split, thus resulting in a lot of duplicate code.

2023-03-14 11:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
> +        '''Fetch all selected nodes in nuke, match against class name if supplied in *options*'''
Will be hard to enforce without automisations/black support, have set editor to show a ruler at 80 chars that might help detecting this during dev.

2023-03-14 11:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
> +            ):
This collector should have the same functionality as the node collector, allowing users to provide class name filters.

2023-03-14 11:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
> +            result = {'image_sequence_path': image_sequence_path}
Split up in separate movie collector now.

2023-03-14 11:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
Agree to split, thus resulting in a lot of duplicate code.

2023-03-15 09:16 UTC, lluisCM requested changes
See comments

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/nuke_movie_publisher_collector.py
> +        return [result]
Better if we declare result at line 33 so we make sure that if the code not enter in any condition it will have an emty result.

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/nuke_movie_publisher_collector.py
> +            media_path = options.get('media_path')
align to unreal. movie_path

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/nuke_sequence_publisher_collector.py
> +            media_path = options.get('media_path')
align to unreal: image_sequence_path

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +    def media_path(self):
movie_path

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +        else:
elif mode== 'render'

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +        self.node_names = self.options.get('node_names', [])
Why we want node_names in options? node_names should be the result of the fetch, but not an option of the plugin, as node_names is just used in the interface, so from that list we will only check one. In case, what could be an option for the plugin is the desired node_name, a string.

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +                mode = 'render_selected'
```suggestion
         mode = 'render_selected'
        if self._pickup_rb.isChecked():
            mode = 'pickup'
        elif self._render_create_write_rb.isChecked():
                mode = 'render_create_write'
```

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +        if len(node_name or '') > 0:
isn't enough just doing `if node_name`?
Also probably cleaner to do something like:
```
if not node_name:
    if 'node_name' in self.options:
            del self.options['node_name']
    return None

< ALL THE OTHER CODE HERE >
```

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +                media_path = os.path.join(render_path, collection.format())
We want the user to pick a file because it may have multiple sequences in the same folder (That was a request from Benn in Unreal).

We have an utility to do that in unreal. `image_sequence_path = unreal_utils.find_image_sequence(image_sequence_path)`
Probably worth moving it to pipeline utils and picking it from there.

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +                if self.media_path is not None and len(self.media_path) > 0
```suggestion
                if self.media_path:
```

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                render_from_image_sequence = result.get('render', False)
thisis not used...

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        if media_path is not None and len(media_path) > 0:
if not media_path

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        if image_sequence_path is not None and len(image_sequence_path) > 0:
if not image_sequence_path

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        else:
elif ==

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        if len(node_name or '') > 0:
isn't enough just doing if node_name?
Also probably cleaner to do something like:

```
if not node_name:
    if 'node_name' in self.options:
            del self.options['node_name']
    return None

< ALL THE OTHER CODE HERE >
```

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
Same comments as in the nuke_sequence_publisher_collector_options

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                delete_read_node = False
not used

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                                write_node[k].setValue(v)
Isn't this code duplicated 2 more times? Maybe worth creating a method for it.

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                if options.get('to_temp'):
Why merging the reviewable_publisher code with the movie publisher code if they use different code? isn't simpler to have 2 different plugins? one for the movie publisher and one for the reviewable which will be used in many definitions.

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/widget/nuke_movie_publisher_exporter_options.py
> +        default_codec = self.options.get('codec', 'mp4v')
if you add this line then you can remove line 109.

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/widget/nuke_sequence_publisher_exporter_options.py
>              self.set_option_result(text, 'image_format')
I think we should do this one as the other update_fn.

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/validators/nuke_writable_node_publisher_validator.py
> +                break
Why this one if you have a break before?

2023-03-15 09:16 UTC, lluisCM commented on resource/plugins/python/publisher/validators/nuke_writable_node_publisher_validator.py
> +        if node_name:
```
if not node_name:
    self.logger....
    return False
< Rest of the code here>

```

2023-03-15 12:06 UTC, lluisCM requested changes
See comments.

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        if movie_path and len(movie_path) > 0:
```suggestion
        if movie_path:
```
Basically the `len(movie_path) > 0:` checks if movie_path == '' and the if movie_path already checks that.

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        if image_sequence_path and len(image_sequence_path) > 0:
same comment as before.

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        if len(node_name or '') == 0:
```suggestion
        if not node_name:
```

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +                1 if self.movie_path and len(self.movie_path) > 0 else 0
```suggestion
                1 if self.movie_path else 0
```

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +        if image_sequence_path and len(image_sequence_path) > 0:
```suggestion
        if image_sequence_path:
```

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +            self.image_sequence_path = self.options['image_sequence_path']
```suggestion
        self.image_sequence_path = self.options.get('image_sequence_path')
```

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +        if len(node_name or '') == 0:
```suggestion
        if not node_name:
```

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +            filter='All files (*)',
Better to filter by image types only.

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        if image_sequence_path and len(image_sequence_path) > 0:
```suggestion
        if image_sequence_path:
```

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
>                  and len(self.image_sequence_path) > 0
```suggestion
                if self.image_sequence_path:
```

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                    finally:
If you use try why don't we catch the exception?

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +            finally:
same here

2023-03-15 12:06 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                if options.get('to_temp'):
Still think that this one should go to reviewable exporter

2023-03-15 14:30 UTC, henriknorin-ftrack reviewed
Committing PR comments that were left pending

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        else:
I want to fall back (see comment below), if unknown mode, on render

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +        else:
Same comment as below, I want to fall back on render if unknown mode.

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +        self.node_names = self.options.get('node_names', [])
Yes, let's guide developers to modify the fetch function instead. The only case if you want to have a no-code solution to provide a predefined set of write notes, but then they would need to block the fetch which requires code anyway.

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/collectors/widget/nuke_sequence_publisher_collector_options.py
> +                media_path = os.path.join(render_path, collection.format())
I'll move to pipeline utils and provide a separate PR, good to have for other DCC:s

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                render_from_image_sequence = result.get('render', False)
Well spotted

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                                write_node[k].setValue(v)
Moved to helper method.

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                if options.get('to_temp'):
The reviewable plugin will be almost identical to the movie, and when we revisit the behaviour of core finaliser removing the reviewable file they will be 100% identical - IMO not worth the effort of maintaining identical code.

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/validators/nuke_writable_node_publisher_validator.py
> +                break
There is now way in python to break out of all loops, only the innermost (https://medium.com/techtofreedom/5-ways-to-break-out-of-nested-loops-in-python-4c505d34ace7)

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                    finally:
The intention of the try is not to catch an exception, is is standard procedure for cleaning up after a section code have executed.

2023-03-15 14:30 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +            finally:
See comment above

2023-03-15 14:32 UTC, henriknorin-ftrack commented
> Still think that this one should go to reviewable exporter

The only reason I see to have it separate is if users want to change the logic, but that should not be needed as we have proper support for setting file format and codec with the options from definition. I would not create even more duplicate code to maintain at this point.

2023-03-16 09:42 UTC, lluisCM requested changes
Please see comments.

2023-03-16 09:42 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
> +        if movie_path and len(movie_path) > 0:
isn't the code commited?

2023-03-16 09:42 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                    finally:
Then you don't need the Try to do that, code will be lees indented if you remove the try and  do the if restore_file_path....

2023-03-16 09:42 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +            finally:
Same comment as above , don't need a try here.

2023-03-16 09:42 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                if options.get('to_temp'):
Ok, just leave it as it is. I think in general this code is over complicated, difficult to maintain and to follow and not aligned with other DCCs. If we start simple, with a reviewable plugin for reviewable, a movie plugin for movies, and a image sequence plugin for image sequences, its easier for the users and for us to identify what is what, and is also align with the other DCCs. In case there is a lot of duplicated code in the widget and it really makes sense to merge it, the widget could be just one, and then with the correct use of the base exporter plugin of nuke we shouldn't have to much duplicated code....

2023-03-16 09:42 UTC, lluisCM commented on resource/plugins/python/publisher/collectors/widget/nuke_movie_publisher_collector_options.py
>                  message = 'No image sequence selected!'
```suggestion
            if self.image_sequence_path:
                message = '1 image sequence selected'
                status = True
            else:
                message = 'No image sequence selected!'
```
Same for the other num_objects. Doesn't really make sense.

2023-03-16 09:42 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                    if file_path is None or not os.path.splitext(
```suggestion
                    if not file_path or not os.path.splitext(
```

2023-03-16 09:42 UTC, lluisCM commented on resource/plugins/python/publisher/exporters/nuke_sequence_publisher_exporter.py
> +                    if file_path is None or os.path.splitext(
```suggestion
                    if not file_path or os.path.splitext(
```

2023-03-16 10:08 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +            finally:
In this particular case, we could benefit from adding an exception catch, as operations might fail due to user errors (missing folders on disk etc)

2023-03-16 10:08 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                if options.get('to_temp'):
I semi agree, the code is a result of framework not having the mechanism for pre-rendering the output (discussed before in separate thread). With that functionality, the exporters would be much cleaner - for example there would be a **nuke_movie_render_publisher_exporter** plugin that executes before **nuke_movie_publisher_exporter** with no if gates within.

I would first evolve the framework to support these kind of pre (render) exporters instead of trying to move code inte the base classes, which is much more harder for users to maintain. Also I do not think we need to be super strict on aligning with other DCC:s, as they are very different in behaviour and must be allowed to differ at some point. Keeping it very strict requires a lot of extra dev time and resources, just what we do not have right now.

2023-03-16 10:08 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +                if options.get('to_temp'):
Side note on that, there is a flaw in the Nuke integration from a pipeline perspective when it comes to the reviewable (and thumbnail) - they should always be rendered from the final image sequence or movie chosen. Right now, you cannot choose to have reviewable being based on these in all cases. For example the thumbnail is always rendered now from selected node now, which could be totally different from the picked up image sequence/movie.

2023-03-16 10:08 UTC, henriknorin-ftrack commented on resource/plugins/python/publisher/exporters/nuke_movie_publisher_exporter.py
> +            finally:
Also added the same exception catch in **nuke_sequence_publisher_exporter.py**

2023-03-16 10:29 UTC, lluisCM requested changes
Code looks ok, I still think that is overcomplicated and difficult to maintain, and could be much simplified, and less duplicated code just using the base exporters correctly and not mixing up all the code for different components in one plugin... But happy to approve if you decide to not change it.

I did a quick test and image sequence is failing, see the attached images to see the way to reproduce it and the error:

```
Operation failed with error: [{'name': 'collector', 'result': [{'name': 'nuke_movie_publisher_collector', 'options': {'_filters': {}, 'mode': 'render_selected', 'node_name': 'Write1'}, 'result': [{'node_name': 'Write1'}], 'status': True, 'category': 'plugin', 'type': 'collector', 'plugin_type': 'publisher.collector', 'method': 'run', 'user_data': {}, 'message': 'Successfully run :NukeMoviePublisherCollectorPlugin', 'widget_ref': '899c7db0ddbb49c9941616f30a70eabb', 'host_id': 'python.nuke-56f5f4bd869f4c69a3294037577eff6f', 'plugin_id': None}], 'status': True, 'category': 'stage', 'type': 'collector'}, {'name': 'validator', 'result': [{'name': 'common_non_empty_publisher_validator', 'options': {'amount': 1, '_filters': {}}, 'result': True, 'status': True, 'category': 'plugin', 'type': 'validator', 'plugin_type': 'publisher.validator', 'method': 'run', 'user_data': {}, 'message': 'Successfully run :CommonNonEmptyPublisherValidatorPlugin', 'widget_ref': '5a80b059f8d147249f434a2860e7bba4', 'host_id': 'python.nuke-56f5f4bd869f4c69a3294037577eff6f', 'plugin_id': None}, {'name': 'nuke_writable_node_publisher_validator', 'options': {'_filters': {}}, 'result': True, 'status': True, 'category': 'plugin', 'type': 'validator', 'plugin_type': 'publisher.validator', 'method': 'run', 'user_data': {}, 'message': 'Successfully run :NukeWritableNodePublisherValidatorPlugin', 'widget_ref': 'c3ab14e15c524c81b9353edd0ee446d1', 'host_id': 'python.nuke-56f5f4bd869f4c69a3294037577eff6f', 'plugin_id': None}], 'status': True, 'category': 'stage', 'type': 'validator'}, {'name': 'exporter', 'result': [{'name': 'nuke_movie_publisher_exporter', 'options': {'supported_file_formats': ['mov', 'mxf'], 'file_format': 'mov', 'mov': {'codecs': ['rle |Animation', 'appr|Apple ProRes', 'AVdn|Avid DNxHD', 'AVdh|Avid DNxHR', 'h264|H.264', 'mjpa|Motion JPEG A', 'mjpb|Motion JPEG B', 'mp4v|MPEG-4', 'jpeg|Photo JPEG', 'png |PNG', 'v210|Uncompressed'], 'codec_knob_name': 'mov64_codec', 'mov64_codec': 'mp4v'}, 'mxf': {'codecs': ['Avid DNxHR'], 'codec_knob_name': 'mxf_video_codec_knob', 'mxf_video_codec_knob': 'Avid DNxHR'}, '_filters': {}, 'codec': 'mp4v|MPEG-4', 'start_frame': '1.0', 'end_frame': '100.0'}, 'result': None, 'status': False, 'category': 'plugin', 'type': 'exporter', 'plugin_type': 'publisher.exporter', 'method': 'run', 'user_data': {}, 'message': 'Failed to run NukeMoviePublisherExporterPlugin: No movie write node selected!', 'widget_ref': '70d0a9460dad4d7280eaba3dfd3c5414', 'host_id': 'python.nuke-56f5f4bd869f4c69a3294037577eff6f', 'plugin_id': None}], 'status': False, 'category': 'stage', 'type': 'exporter'}]
```


<img width="609" alt="Screenshot 2023-03-16 at 11 24 54" src="https://user-images.githubusercontent.com/112543804/225589523-86ada54b-a619-48dd-811a-571dabc831f8.png">


<img width="542" alt="Screenshot 2023-03-16 at 11 25 17" src="https://user-images.githubusercontent.com/112543804/225589511-420966dd-7e40-46fd-bd24-a597985ec36b.png">

2023-03-16 11:15 UTC, lluisCM approved these changes

2023-03-16 11:21 UTC, merged